// Copyright (C) 2015 BK

#ifndef SRC_INTERPOLATIONTYPES_H_
#define SRC_INTERPOLATIONTYPES_H_

enum INTERP_TYPE {
  GAUSSIAN_NOISELESS = 0,
  GAUSSIAN_NOISY,
  MULTILEVEL_B_SPLINE,
  TOTAL_INTERP
};

#endif  // SRC_INTERPOLATIONTYPES_H_
